version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports: 
        - "3000:80"
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
 
    environment:
      - PORT=3000
      - MONGO_USER=root
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
      

    volumes:
      - mongo-db:/data/db
  redis:
    image: redis:latest
   

volumes:
  mongo-db: